import './globals.css'
import type { Metadata } from 'next'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <Script type="module" src="https://unpkg.com/@splinetool/viewer@0.9.388/build/spline-viewer.js" />
      </head>
      <body>{children}</body>
    </html>
  )
}
